src/server/queue/index.js
This can cause issues where stale data is displayed in the web interface, if the actual `Queue` instances have `sendEvents` disabled (or if Arena's `Queue` ends up out of sync somehow).
=> Disable caching, events for bee-queue

src/server/views/dashboard/queueDetails.js, src/server/views/dashboard/queueJobsByState.js
According to the [API](https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queuegetjobcounts), there should be no parameter given while calling bull's `Queue.getJobCounts`.
=> Resolved bee-queue/arena#39

src/server/views/partials/dashboard/jobDetails.hbs
Fix logic for displaying progress bar section of job detail page.
Don't display the progress bar section at all if the Queue type is Bee. If the queue is not Bee (ie, it's Bull) then display the progress display, but use it as `_progress` instead of `progress`
=> Resolve #45 - progress bar display

src/server/views/dashboard/templates/queueJobsByState.hbs, src/server/views/helpers/handlebars.js
Currently the raw job id is passed directly into the HTML of collapse div ids.
This causes problems when job ids have spaces or colon (:) characters.
This pull request escapes job ids before inserting them in to the HTML, allowing individual jobs to be viewed in the list.
=> Update Jobs List UI to handle special characters in ids

src/server/views/api/bulkAction.js
The UI sends an array of url encoded Job Ids when doing things like Bulk Remove Jobs. 
This change allows the server to decode these ids to resolve to the correct job id.
=> Support bulk actions on jobs with encoded characters

README.md, src/server/queue/index.js
Both Bull and Bee allow `redis` in their config to be a URL or an object.
We're using Redis-URL to connect to redis so this patch adds an optional `url` field.
If given, it will be used to construct Redis configuration instead of `host`, `port`, `db` and `password`.
=> Allow Arena to connect to queues using a Redis URL.

public/dashboard.css, src/server/views/dashboard/templates/queueJobsByState.hbs, src/server/views/helpers/handlebars.js, src/server/views/layout.hbs, src/server/views/partials/dashboard/jobDetails.hbs
1. Added `<pre>` formatting using `highlight.js`
2. Fixed an issue with the `<pre>` tag and whitespace control when viewing the template inline
3. Set a max height of 250px to the `<pre>` tag with overflow-y: scroll
4. Put the "Permalinks" on a new row so that long id's don't overflow outside of tag (we used uuid.v4() for instance, a pretty long id)
5. Formatted `this.returnvalue` using the json helper as well in case the returnvalue is not just a string
If you don't want to accept all changes, I can make a separate pull request for just the whitespace control so that the `<pre>` tags look proper on the inline view.
=> Styling and formatting fixes for jobDetails view

README.md, src/server/queue/index.js
This PR fixes #67. 
It also fixes a bug related to Bull configuration. Creating a Bull queue using a URL as configuration is done by passing it as a string 2nd argument, not as `{url}` object 2nd argument: https://github.com/OptimalBits/bull#basic-usage
I also enhanced the documentation a bit.
=> Custom Redis connection; documentation

src/server/queue/index.js
https://github.com/bee-queue/arena/pull/85/files#diff-623167d1c54ecd199ee8a745a96c568fL60
As you can see here, there was no way that `url` could ever be used as `options` was always guaranteed to exist. Since the Bee and Bull branches are very similar, I hoisted the `options` declaration out of the if/else statement.
=> Fix Bull queue construction so the url option is respected.

src/server/views/helpers/handlebars.js
I noticed this vulnerability when I added a job to Bull that had job data that included some HTML. Since the `json` Handlebars helper assumes that its input is safe, any HTML that is rendered onto the job details page will be considered valid, including `<script>` tags.
You can repro this by creating a job in Bull (and maybe in Bee?) with data along the lines of
```json
{
"something": "<script>alert('Hello there!')</script>"
}
```
and then opening up the `queueJobsByState` page that includes the job with unsafe HTML. You'll see an alert.
bug is in this helper function: https://github.com/bee-queue/arena/blob/be866d368b44f95dbe4424ba71d6b5ec7d7843e9/src/server/views/helpers/handlebars.js#L5
I've attached a fix in which all string values are escaped when the object is stringified.
=> json Handlebars helper allows unsafe HTML

src/server/views/partials/dashboard/jobDetails.hbs
As of bull 3.4.2 (and probably earlier), the progress of a job is provided in `progress`, not `_progress`. This commit updates the view template to match.
This fixes a problem where the progress of any bull job would always appear in arena as "0%". Now the correct progress is shown.
See: https://github.com/OptimalBits/bull/blob/v3.4.2/lib/job.js#L129
=> Ensure job progress is displayed (compatibility with latest version of bull)

package.json
We shouldn’t use it to develop on the module, but users should be able to use
it to install the module just fine.
Fixes https://github.com/bee-queue/arena/issues/99.
=> Allow Yarn again

src/server/views/dashboard/queueJobsByState.js
Clicking through to the state page was broken with this code. `jobTypes` does not exist in function.
Fixes #110
=> Fix bug when clicking through to state page

index.js, src/server/app.js, src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/queueDetails.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/dashboard/queueList.js
Fixes #105 but also allows for the route to have a wildcard
```
const arena = Arena({
queues: [
{
// ...
}
],
}, {
basePath: '/jobs',
disableListen: true,
});
// [...]
app.use('/user/:id', arena);
```
Will result in a path /user/:id/jobs which can then be matched to an actual url like user/1/jobs
=> fix: base path with nested routes which may have wildcards

src/server/queue/index.js
Currently Arena does not pass forward any TLS opts it receives as part of the Redis config. If a TLS opt is supplied, it should be passed to the queue Redis configuration so that Arena can read from TLS-enabled Redis instances.
=> Support Redis-over-TLS

src/server/queue/index.js
Hey there, thanks for the handy GUI!
This change makes it possible to control the creation of Redis clients when using Bull, instead of having a new connection created for each and every queue. It uses the pattern documented by Bull [here](https://github.com/OptimalBits/bull/blob/master/PATTERNS.md#reusing-redis-connections) which is helpful if you have many queues and not so many connections available.
There's already a similar feature for Bee-Queue, where you can pass a node_redis instance in the `redis` option, so I've only added this option for Bull.
=> Support passing createClient to Bull

src/server/views/dashboard/templates/queueJobsByState.hbs, src/server/views/helpers/handlebars.js
Fixes #116 
I did try escaping these characters first but it did not seem to help at all, so just went with a hash since the result is not currently being used for anything other than generating a unique attribute value.
=> Fixes issue preventing expand/collapse functionality from working when job ids contain special characters

src/server/views/layout.hbs
On small screens (e.g. mobile devices) the `navbar` at the top of the screen does **not** function due to the missing reference to the `div`.
=> Fixing navbar toggle in the main layout

public/dashboard.js, src/server/views/layout.hbs
The shiny new "add job" ✨codes need to follow the basePath prefix convention used elsewhere in order for everything to work correctly when a basePath is set – currently the JS/CSS assets won't be loaded, and the API request will 404!
=> Fix "add job" vendor/API path when basePath is set

src/server/views/dashboard/jobDetails.js
Prior to this change, retrieving json job details would always fail
with `TypeError: Converting circular structure to JSON`. After this
change, the json value loads correctly.
=> Omit circular json structures from JSON responses

package.json, src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/partials/dashboard/jobDetails.hbs
Display Job logs on the job details page. It will help to easily view the logs associated with the job while processing it.
_NOTE: Bull Queue version updated to the latest 3.12.1 since the older version does not support adding or getting logs for the Job._
=> Changes for Displaying Job logs in Job Details

src/server/queue/index.js, src/server/views/api/jobRetry.js, src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/partials/dashboard/jobDetails.hbs
We currently use [Agenda](https://github.com/agenda/agenda) paired with [AgendaDash](https://github.com/agenda/agendash). One of the features AgendaDash provides is an ability to run jobs at any time, not just when they are failed state. We consider this a core feature that any replacement should have. 
We are moving to Bull/Arena and would love this feature to be included.
=> Run jobs on demand

src/server/app.js
Currently if you build the application with zeit/pkg you will not be able to run it due to a temporary snapshot path. Making it relative will allow pkg to ship the default config with the binary file.
Fixes following error:
(node:24280) UnhandledPromiseRejectionWarning: Error: Cannot find module '/snapshot/api/node_modules/bull-arena/src/server/config/index.json'
=> Change defaultConfig require path to relative

src/server/views/dashboard/templates/queueDetails.hbs
Resolves #208 and #53
Adds `code` and `text` modes to the jsoneditor. (as well as original `tree` mode)
I also expanded the jsonEditor height to 300px. More vertical space was required for `tree` mode popover prompts and `code` / `text` editor parse warn messages.
Please let me know if there is anything else I can do to get this Pull Request merged in. Thanks for the useful tool.
=> Add jsoneditor code and text mode options

src/server/views/dashboard/queueJobsByState.js
When attempting to access job details by status using Bull@3.18.1 and bull-arena@3.3.2 the following exception is thrown:
```
(node:43624) UnhandledPromiseRejectionWarning: TypeError: function is not iterable (cannot read property Symbol(Symbol.iterator))
at Function.all (<anonymous>)
at _html (/work/xxxxxxxx/xxxxxxxx/xxxxxxxx/node_modules/bull-arena/src/server/views/dashboard/queueJobsByState.js:105:15)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:43624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the …
```
=> Fixed job listing for Bull

src/server/queue/index.js, src/server/views/dashboard/queueDetails.js, src/server/views/helpers/queueHelpers.js
Support for [bullmq](https://github.com/taskforcesh/bullmq)
issue: #248 
Pending changes -
@types/bull-arena in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)
=> add support for bullmq

src/server/queue/index.js
BullMQ takes redis connections options in the format `{ connection: { host: ... }  }` instead of `{ redis: { host: ... } }`. 
This works well with connection settings as strings, havent tested passing in ioredis object
=> Support redis connection options in BullMQ

package-lock.json, package.json, src/server/app.js, src/server/views/helpers/handlebars.js
This pull request removes the dependency on handlebars-helpers by creating ad hoc helpers to do the same tasks.
This removes 135 transitive dependencies, making node_modules much lighter, and removes 64 vulnerabilities.
This is a continuation of pull #227 
Closes #226
=> feat(deps): remove dependency on `handlebars-helpers`

public/dashboard.js
When clicking on add job, would be nice to change the message of that button, so people would know that by clicking again, the editor will be hidden. This PR tries to handle this.
=> Change add job text depending on hide prop on dashboard

src/server/views/dashboard/queueJobsByState.js, src/server/views/dashboard/templates/queueJobsByState.hbs
When showing the jobs list by state, would be nice to have the last created jobs at the top, this PR tries to handle that by applying ordering desc by default. Also I added a dropdown for ordering so a user could choose how to order jobs by id
#240 
tested with #326
=> Apply ordering for jobs when using Bull queue

CONTRIBUTING.md, README.md, example/README.md, example/index.js, example/package.json
In reviewing PR https://github.com/bee-queue/arena/pull/324 I realized that there was no easy way to run the queue locally. This adds a basic working example and some simple documentation.
=> feat: add contributing guidelines and working example

example/bee.js
Helps test PRs like https://github.com/bee-queue/arena/pull/334.
This is low risk since the code change is isolated only to the example code.
=> feat: better example showing jobs move through states

README.md, example/README.md, src/server/views/helpers/handlebars.js, src/server/views/partials/dashboard/jobDetails.hbs
This PR fixes the capitalize function since is not using the real value that is passed. Also I'm adding processed on and finished on values in jobDetails
=> Fix capitalize function

example/bull.js, src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/helpers/handlebars.js, src/server/views/partials/dashboard/jobDetails.hbs
In order to prevent a loading time when we have 1000 jobs in our tables, we could just show the logs when we click in job button for standalone page, this PR should solve #220
=> Fix performance in job details

.gitignore, public/dashboard.js, src/server/views/api/bulkAction.js, src/server/views/api/bulkJobsPromote.js, src/server/views/api/index.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/dashboard/templates/queueJobsByState.hbs
This is a new feature to allow us to promote multiple delayed jobs by Promote Jobs button. #203 
This feature is only allowed in Bull and Bullmq
1. go to example directory and run: npm run start:bull
2. go to delayed table
3. check the delayed job
4. click on Promote Jobs button
5. check the the delayed job, now is in active table
=> Adding Promote Jobs button

example/bullmq.js, example/package.json, src/server/views/dashboard/index.js, src/server/views/dashboard/queueDetails.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/helpers/queueHelpers.js
This PR adds a new state that is supported in bullmq: waiting-children, also is added the example into the example bullmq file.
It's suppose to add a new bullmq state so should only be related to see in the example
Go to example directory and run: npm run start:bullmq
There are 2 queues, parentQueue should have 1 job in waiting-children state
If some of the children fails, we can retry those with the retry button
when those children are completed, the parent job in parentQueue should be processed
=> Support waiting-children state for bullmq

example/package.json, package.json, public/dashboard.js, src/server/views/api/index.js, src/server/views/api/queuePause.js, src/server/views/api/queueResume.js, src/server/views/dashboard/index.js, src/server/views/dashboard/queueDetails.js, src/server/views/dashboard/templates/queueDetails.hbs, src/server/views/helpers/queueHelpers.js
This PR fixes handlebars vulnerability #390 and I noticed that from bull, when entering to paused page is getting an error, so I fixed that issue too, as bullmq has paused state too, I also added it to it.
Now we are allowed to enter to paused state page without errors
1.Go to example directory
2.Run: npm run start:bull
3.Enter to the first queue
4.Click in pause button
5.Enter to paused state, you should enter to that page without error, and for those active job should be in paused state
4.Same case for bullmq
This PR is taking advantage of #375
=> Fix handlebars and paused state

example/bullmq_with_flows.js, public/dashboard.js, src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/helpers/jobHelpers.js, src/server/views/partials/dashboard/jobDetails.hbs
Adding parentId and children info on JobDetails and QueueJobsByState views.
No potential risks
1. Run the example `npm run start:bullmq_with_flows`
2. Go to the parent queue, and when clicking on the job details, two new sections will appear: parent and children, from which we can navigate to the respective parent and children.
=> Add parent children to job details

src/server/views/dashboard/jobDetails.js, src/server/views/partials/dashboard/jobDetails.hbs
This PR adds the counter of jobs for processed and unprocessed children into jobDetails logic and template.
1. Go to example directory.
2. Run npm run start:bullmq_with_flows
3. Go to waiting-children state in parent queue
4. Select the parent job
5. Go to the perma link to see job details
6. You should see the number of children for processed and unprocessed.
=> Add children counters

example/bullmq.js, example/bullmq_with_flows.js, example/package.json, src/server/views/dashboard/jobDetails.js, src/server/views/partials/dashboard/jobDetails.hbs
This PR adds pagination for children, since getDependencies has options to do it. Note: Pagination is working with cursors so we could only go from one side, we cannot go back. This is the only limitation because  of how those dependencies are saved in Redis.
No potential risk.
1. Go to example directory.
2. Run npm run start:bullmq
3. Go to waiting-children state in parent queue
4. Select the parent job
5. Go to the perma link to see job details
6. You should see a button for children to >> go to the next children jobs. there is a min count of children that is 25 to be showed.
=> Use pagination with children

example/bullmq_with_flows.js, example/package.json, public/dashboard.js, src/server/views/api/addFlow.js, src/server/views/api/getFlow.js, src/server/views/dashboard/templates/flowDetails.hbs, src/server/views/helpers/flowHelpers.js
This PR adds perma links on tree view, so we can easily go to an specific job details page from tree view.
No potential risks
1. Go to example directory
2. Run npm run start:bullmq_with_flows
3. Go to the first flow connection
4. Create a flow, for example using:
```
{
"name": "parent-job",
"queueName": "name_of_my_parent_queue",
"data": {},
"children": [
{"name": "child","data": {"idx": 0, "fo": "bar"}, "queueName":"name_of_my_queue"}
]
}
```
5. You should see the tree view and if you click to the name of each node, you should go to that job detail
6. Also if you look for that flow using, same behaviour of perma links should work.
=> Use perma links on nodes tree

src/server/views/partials/dashboard/jobDetails.hbs
fixes #416
Added `encodeURI` to job's ID.
None
Check that job IDs such as `41fc5496-d3c1-4bba-8eac-1abdeaaa3e47:https://olliechick.co.nz/` now work from the jobs page.
=> fix(job-details): encodeURI of job ID for URL

src/server/queue/index.js
Bull no longer allows passing the URL directly as the value of
`options.redis`. Instead, pass URL as a separate argument when present.
See https://github.com/OptimalBits/bull/issues/2118 for additional
context.
Specifying the Redis URL under the `redis` key instead of `url` would have worked before's Bull's changes but this PR doesn't attempt to address that scenario.
Using the `url` config with the latest version of Bull should demonstrate the fix. This should also work on older versions of Bull, the way it was previously handled here only worked by accident.
=> Update how Redis URL is passed to Bull

example/bull.js, public/dashboard.js, src/server/views/api/index.js, src/server/views/api/repeatableJobRemove.js, src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/partials/dashboard/jobDetails.hbs
Add new button to remove repeatable jobs if a job is linked to one
None, this should be only be visible for bull package
Make sure there is not repeatable job in delayed state when you click remove repeatable button
=> feat(bull): support removing repeatable jobs

README.md, src/server/views/api/repeatableJobRemove.js, src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/queueJobsByState.js
Allow to remove repeatables for bull in version that do not have key in options
=> fix(remove-repeatable): consider old versions of bull

src/server/views/dashboard/queueDetails.js, src/server/views/helpers/queueHelpers.js
Added additional [JobState](https://api.docs.bullmq.io/types/v4.JobState.html) recently introduced.
Reference: https://docs.bullmq.io/guide/jobs/prioritized
Reference: https://bullmq.io/news/062123/faster-priority-jobs/
Tested on older bullmq and it ignores the prioritized state since it doesn't exist.
=> feat(bullmq): support prioritized job state

docker-compose.yml, example/bee.js, example/bull.js, package.json, public/dashboard.js, src/server/app.js, src/server/views/api/index.js, src/server/views/api/jobDataUpdate.js, src/server/views/dashboard/templates/jobDetails.hbs, src/server/views/partials/dashboard/jobDetails.hbs
=> feat(details): update job data
