README.md, index.js, package.json, src/server/app.js, src/server/authorizer.js, src/server/bull/index.js, src/server/config/index.json, src/server/views/api/bulkAction.js, src/server/views/api/jobRemove.js, src/server/views/api/jobRetry.js, src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/queueDetails.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/dashboard/queueList.js, src/server/views/layout.hbs
=> Make bull ui deploy friendly

src/server/bull/index.js
added db and password options to redis configuration
=> added support for redis database and password

README.md, src/server/bull/index.js
=> Added support of queue prefix configuration

README.md
The host and container placeholders are reversed.
=> Fix the docker run command in the readme

src/server/views/dashboard/templates/queueJobsByState.hbs
=> fix basePath in page link

README.md
Clarify the README such that it displays accurate configuration information for running as a Node module.
=> Fixes issue #64

package.json, yarn.lock
This fixes a crash of the Arena UI when the job completes.
=> updated bull to 3.3.7

README.md, index.js
add listenOpts host for selecting ip of host to listen on
=> add host opt

src/server/views/partials/dashboard/jobDetails.hbs
=> Fix bull job progress

package-lock.json, package.json
=> Upgrade nodemon

Dockerfile
Create alpine Dockerfile based on node best practices.
info: https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md
Closes #104
=> chore(dockerfile): use optimised alpine based image

package-lock.json, package.json
Fix for vulnerability:
https://nodesecurity.io/advisories/745
Relates to [this](https://github.com/bee-queue/arena/pull/140) incomplete PR, but since its author is nowhere to be found for the past 2 months, I decided to make a new one.
=> Bumped handlebars-helpers version to fix vulnerability.

.gitignore, index.js, package-lock.json, package.json, public/dashboard.css, public/dashboard.js, src/server/app.js, src/server/config/index.json, src/server/queue/index.js, src/server/views/api/index.js, src/server/views/api/jobAdd.js, src/server/views/dashboard/templates/queueDetails.hbs, src/server/views/dashboard/templates/queueList.hbs, src/server/views/helpers/queueHelpers.js, src/server/views/layout.hbs
I pulled in #55 and cleaned up the merge conflicts also picking up a few changes that @skeggse and I had asked for. I'll merge this in and cut a release so that we can get this into folks hands.
=> Merge in job cleanup code

package-lock.json, package.json
see https://www.npmjs.com/advisories/755
=> bump handlebars to ^4.0.14

package-lock.json, package.json
Hi 👋🏼,
According to [snyk](https://snyk.io/) tests, there are some packages that contain vulnerabilities.
I've created a PR which with an upgrade to fix this.
Example:
https://snyk.io/vuln/SNYK-JS-HANDLEBARS-469063
=> Upgrade packages for security issues

public/dashboard.js
Fix "Add Job" functionality default json being an invalid JSON.
=> Fix "Add Job" functionality

CHANGELOG.md
Not #210
https://github.com/bee-queue/arena/pull/201
=> PR for 2.7.0 update was #201

src/server/views/api/jobRetry.js
=> Fix job retry

public/dashboard.js
=> Encode url for the action 'add job'

public/dashboard.js, src/server/queue/index.js, src/server/views/api/jobAdd.js, src/server/views/dashboard/queueDetails.js, src/server/views/dashboard/templates/queueDetails.hbs
Adds support for named jobs with Bull queues.
Fixes https://github.com/bee-queue/arena/issues/170 without polluting the job data with special properties.
=> Added support for named jobs

src/server/views/api/jobRetry.js
#223 broke retries and delayed job triggering.
Fixes #234.
=> fix(retry-job): [backport] include job name

src/server/views/api/jobRetry.js
#223 broke retries and delayed job triggering. @roychri does this seem right?
Fixes #234.
=> fix(retry-job): include job name

src/server/views/dashboard/jobDetails.js, src/server/views/dashboard/templates/jobDetails.hbs, src/server/views/partials/dashboard/jobDetails.hbs
=> Display stacktraces when job is in deplayed or completed state

src/server/views/layout.hbs
=> fix(deps): use correct bootstrap css

src/server/views/dashboard/queueJobsByState.js
From #201. cc @Subv, @ganeshcse2991, @robman87
Possibly related to #204, #220.
=> fix(job-details): correctly wait for promises

README.md
=> bullmq docs: update readme docs

src/server/views/dashboard/templates/queueJobsByState.hbs
=> #241 - Don't use name from job data

example/bull.js, package-lock.json, package.json, public/dashboard.js, src/server/views/api/bulkAction.js
Retry bulk button is throwing an error because the action is not the correct one as in delayed status is sending remove only as action, now it handles the retry action too. Also I upgraded jsoneditor as in ·#309 and still works as expected from example folder
=> Fix retry bulk action

example/README.md
=> docs: fix readme instructions on how to run examples

.gitignore
=> chore: ignore sublime IDE file

.prettierignore, README.md
Fixes misplaced parameters that I overlooked when reviewing https://github.com/bee-queue/arena/pull/347.
None. This is documentation only.
None. This is documentation only.
=> fix: fixes misplaced parameters

README.md, example/bull.js, example/public/example.js, src/server/app.js, src/server/views/layout.hbs
This PR is for customizing the layout by providing a new feature: customJsPath, so it could be pass as a param. In order to test this PR:
1. Go to examples
2. Run: npm run start:bull
3. You should see a google link in nav bar at the button
=> Adding customJsPath options

.lintstagedrc
There is an error when releasing, this is related to a conflict when eslint check the changes in changelog, that is generated by the release process, so deleting md would fix it.
We will be good since pretty quick will be triggered too to fix the changed files.
Releases should pass
=> Applying eslint only to js to avoid conflicts with changelog

example/bullmq.js, example/package.json, src/server/views/dashboard/queueJobsByState.js, src/server/views/dashboard/templates/queueJobsByState.hbs, src/server/views/helpers/handlebars.js, src/server/views/partials/dashboard/jobDetails.hbs
Consider delayed markers, show missing id in this case, should fix https://github.com/bee-queue/arena/issues/600
=> fix(bullmq): consider delayed markers

example/README.md, example/bee.js, example/bull.js, example/bullmq.js, example/bullmq_with_flows.js, example/docker-compose.yml, example/express.js, example/fastify.js, example/package.json
No risk
execute every example using the new redis container
=> chore: use redis container for testing

example/package.json, package-lock.json, package.json, src/server/views/dashboard/index.js, src/server/views/dashboard/queueDetails.js
BREAKING CHANGE: add new prioritized state, previous versions of bullmq wont't see this state
Support prioritized state, new page should be shown
No
=> feat(bullmq): support prioritized state

example/bullmq.js, src/server/views/api/repeatableJobRemove.js, src/server/views/dashboard/queueJobsByState.js
Support Remove Repeatable button on delayed jobs for bullmq
None
=> feat(bullmq): support removing repeatable jobs

src/server/views/layout.hbs
Just adding the favicon as its not showing
=> add-favicon: implictly include favicon at layout template

public/dashboard.js, src/server/queue/index.js, src/server/views/api/jobAdd.js, src/server/views/dashboard/queueDetails.js, src/server/views/dashboard/templates/queueDetails.hbs
Provide editor for adding options
None
=> feat(add-job): provide editor for adding options in bull and bullmq

public/dashboard.js, src/server/views/api/bulkAction.js, src/server/views/api/bulkJobsClean.js, src/server/views/api/index.js, src/server/views/dashboard/queueJobsByState.js, src/server/views/dashboard/templates/queueJobsByState.hbs
=> feat(finished): add clean jobs button

src/server/views/api/bulkAction.js
validate jobs length in bulk action
=> fix(jobs): validate jobs length in bulk action

example/package.json, package-lock.json, package.json, src/server/views/dashboard/queueJobsByState.js
=> fix(bull): retry only failed jobs

src/server/views/helpers/flowHelpers.js
consider when there are not children for a single node
None
=> fix(get-flow): consider when there are not children
